require("core.plugin_config.comment")
require("core.plugin_config.gitsigns")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-autopairs")
require("core.plugin_config.nvim-cmp")
require("core.plugin_config.neo-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.toggleterm")
require("core.plugin_config.treesitter")
require("core.plugin_config.spectre")
require("core.plugin_config.colorizer")
require("core.plugin_config.oil")
require("core.plugin_config.alpha")
require("core.plugin_config.noice")
require("core.plugin_config.nvim-ufo")

require("core.plugin_config.lsp.mason")
require("core.plugin_config.lsp.lspconfig")
require("core.plugin_config.lsp.lspsaga")
require("core.plugin_config.lsp.null-ls")
require("core.plugin_config.lsp.dap")
require("core.plugin_config.lsp.aerial")


require("core.plugin_config.which-key")
